// Vite+ per-package settings. `vitest.config.ts` beside this file is vitest's own config (vitest
// prefers it over this one); this file exists only to declare the `test` task that `vp run` executes,
// so the repo-root `pnpm test` picks this package up. Without it vp skips the package silently.
//
// `test` is a task rather than a package.json script because every `vitest run` rewrites the scratch
// paths below and reads them back on the next run, which vp declines to cache unless they are
// declared. `build` stays a plain script (vp forbids a task and a script sharing a name) because the
// Vite build of `app/` is an ordinary input-to-output step vp can track by itself.

// Written and read back by every vitest run, so without these almost nothing caches. Workspace-wide
// because tracking reaches past the package that owns the task. Mirrors
// packages/custom-gatekeeper/vite.config.ts; see cloudflare-os/scripts/vitest-task-vite-config.ts for
// the full accounting of each path.
const vitestScratch = [
  { pattern: "!**/node_modules/.vite/**", base: "workspace" },
  { pattern: "!**/node_modules/.vite-temp/**", base: "workspace" },
  // The capnweb-validate build tree, regenerated by any suite that starts a worker under
  // @cloudflare/vitest-pool-workers. Derived from tracked sources, so dropping it loses nothing.
  { pattern: "!**/.wrangler/**", base: "workspace" },
] as const;

export default {
  run: {
    tasks: {
      test: {
        // Both suites: the workers-pool one in the package root, and the SPA's jsdom one under app/.
        // Same command as the package's `test:run` script, so `vp run test` and `pnpm test:run` agree.
        command: "vitest run && vitest run --config app/vitest.config.ts",
        input: [{ auto: true }, ...vitestScratch],
        output: [{ auto: true }, ...vitestScratch],
      },
    },
  },
};
