import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
const bundle = await build({ entryPoints: ['src/configurator.js'], bundle: true, format: 'iife', write: false });
const html = `<html><body style="font:14px sans-serif;padding:16px"><label>Kernel name <input value="notebook" maxlength="64"></label><p>Each new connection gets a fresh Python kernel. Cloned notebooks do not reuse the original runtime.</p><script>${bundle.outputFiles[0].text.replaceAll('</script', '<\\/script')}</script></body></html>`;
const types = await readFile('src/types.d.ts', 'utf8');
await writeFile('src/generated.ts', `// Generated by scripts/generate.mjs\nexport const TYPES_CODE = ${JSON.stringify(types)};\nexport const CONFIGURATOR_HTML = ${JSON.stringify(html)};\n`);
