// The Data management SPA's build config (app/ → one inlined HTML file). `vite.config.ts` beside
// this file is the Vite+ task file; this one is referenced only by build-app.mjs.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig, type Plugin } from "vite";
import { viteSingleFile } from "vite-plugin-singlefile";

const pkgDir = dirname(fileURLToPath(import.meta.url));
const unminified = process.env.GATEKEEPER_APP_UNMINIFIED === "true";

// Intermediate build output. Under node_modules so it is git-ignored without touching .gitignore.
const OUT_DIR = "node_modules/.data-app-build";

const HEADER = "<!-- Generated from packages/gatekeeper-records/app by build-app.mjs. Do not edit. -->\n";

/** Write the inlined build to src/generated/ for the Worker to import. Skips identical rewrites. */
function emitAppText(): Plugin {
  return {
    name: "emit-app-text",
    closeBundle() {
      const html = readFileSync(resolve(pkgDir, OUT_DIR, "app", "index.html"), "utf8").replace(
        /(<script type="module"[^>]*>)([\s\S]*?)(<\/script>)/,
        "$1$2\n//# sourceURL=app:///gatekeeper/records/gatekeeper-records.js\n$3",
      );
      const contents = HEADER + html;
      const outDir = resolve(pkgDir, "src", "generated");
      mkdirSync(outDir, { recursive: true });
      const write = (file: string, body: string) => {
        const path = resolve(outDir, file);
        if (existsSync(path) && readFileSync(path, "utf8") === body) return false;
        writeFileSync(path, body);
        return true;
      };
      const wroteTxt = write("app.txt", contents);
      // A TS module too, so the Worker can import it without a text-module rule.
      write(
        "app.ts",
        `// Generated by packages/gatekeeper-records/build-app.mjs. Do not edit.\n` +
          `/** The Data management page, a single self-contained HTML document for startAppUi(). */\n` +
          `export const APP_HTML: string = ${JSON.stringify(contents)};\n`,
      );
      console.log(`${wroteTxt ? "wrote" : "unchanged"} src/generated/app.txt (${(html.length / 1024).toFixed(0)} KiB)`);
    },
  };
}

export default defineConfig({
  plugins: [react(), tailwindcss(), viteSingleFile(), emitAppText()],
  build: {
    outDir: OUT_DIR,
    emptyOutDir: true,
    minify: unminified ? false : "terser",
    terserOptions: { compress: { passes: 2 }, format: { comments: false } },
    // Network-isolated iframe: no separate asset files.
    assetsInlineLimit: 100_000_000,
    cssCodeSplit: false,
    sourcemap: false,
    rollupOptions: {
      input: "app/index.html",
      output: { entryFileNames: "gatekeeper-records.js" },
    },
  },
});
