// Generates src/generated.ts: the session .d.ts the Workshop shows agents, and the configurator
// iframe HTML with its bundled script.
import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";

const bundle = await build({ entryPoints: ["src/configurator.js"], bundle: true, format: "iife", write: false, minify: true });
const style = [
  "body{font:14px/1.45 system-ui,sans-serif;margin:0;padding:14px 18px;color:#172033}",
  ".row,.choice{display:flex;gap:10px;align-items:flex-start;padding:8px 10px;border:1px solid #d7dce4;border-radius:8px;margin:6px 0;cursor:pointer}",
  ".row span,.choice span{display:block}.hint{color:#5b6477;font-size:12px}.disabled{opacity:.55;cursor:not-allowed}",
  ".label{font-weight:600;margin:14px 0 4px}.muted{color:#5b6477}#status{color:#5b6477}",
  "@media (prefers-color-scheme:dark){body{color:#e6e9ef;background:transparent}.row,.choice{border-color:#39404d}.hint,.muted,#status{color:#a3abba}}",
].join("");
const html = `<!doctype html><html><head><meta charset="utf-8"><style>${style}</style></head><body>` +
  `<div style="font-weight:600">Approved datastores</div><p id="status"></p><div id="list"></div><div id="access"></div>` +
  `<p class="muted">Records stay in the datastore when a gadget is removed. Several gadgets can share one datastore.</p>` +
  `<script>${bundle.outputFiles[0].text.replaceAll("</script", "<\\/script")}</script></body></html>`;
const types = await readFile("src/types.d.ts", "utf8");
await writeFile("src/generated.ts", `// Generated by scripts/generate.mjs\nexport const TYPES_CODE = ${JSON.stringify(types)};\nexport const CONFIGURATOR_HTML = ${JSON.stringify(html)};\n`);
