// One-off: extracts printable ASCII (32-126) from the Linux console's 8x8 VGA font
// (/usr/share/consolefonts/Lat15-VGA8.psf.gz, console-setup; console fonts are public domain) into
// src/shared/font8x8.js. The generated file is committed, so builds never read the system font.
//
//   node scripts/extract-font.mjs [path/to/font.psf.gz]
import { readFileSync, writeFileSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const src = process.argv[2] ?? "/usr/share/consolefonts/Lat15-VGA8.psf.gz";
const buf = gunzipSync(readFileSync(src));
if (buf[0] !== 0x36 || buf[1] !== 0x04) throw new Error("expected a PSF1 font");
const mode = buf[2];
const height = buf[3];
if (height !== 8) throw new Error(`expected an 8-pixel font, got ${height}`);
const count = mode & 1 ? 512 : 256;
const glyph = (/** @type {number} */ i) => buf.subarray(4 + i * height, 4 + (i + 1) * height);
/** @type {Map<number, number>|null} */
let unicode = null;
if (mode & 2) {
  unicode = new Map();
  let off = 4 + count * height;
  for (let g = 0; g < count; g++) {
    for (;;) {
      const u = buf.readUInt16LE(off); off += 2;
      if (u === 0xffff) break;
      if (u !== 0xfffe && !unicode.has(u)) unicode.set(u, g);
    }
  }
}
const rows = [];
for (let c = 32; c <= 126; c++) {
  const g = unicode ? unicode.get(c) ?? c : c;
  rows.push([...glyph(g)].map((b) => b.toString(16).padStart(2, "0")).join(""));
}
const out = `// Generated by scripts/extract-font.mjs from the Linux console 8x8 VGA font (public domain).
// FONT8X8[c - 32] is 16 hex digits: 8 rows, top first, most significant bit leftmost.
export const FONT8X8 = [
${rows.map((r) => `  "${r}",`).join("\n")}
];
`;
writeFileSync(join(dirname(fileURLToPath(import.meta.url)), "../src/shared/font8x8.js"), out);
console.log(`wrote ${rows.length} glyphs`);
