// Code generation for the Records SDKs from the OpenAPI document (pure functions; generate.ts
// writes the files, and __tests__/generate.test.ts checks the committed output is current).
//
// What is generated, from the document alone:
//   TypeScript  src/generated/types.ts   one type per component schema, one query type per operation
//               src/generated/client.ts  the operation table and `RecordsClient`, one method per
//                                        operation plus an async iterator per paginated operation
//   Python      python/records_sdk/_generated.py  TypedDicts, the operation table and the client
// The runtime behaviour (idempotency keys, retries, Retry-After, 412 → RevisionConflictError) lives in
// hand-written runtimes (src/runtime.ts, python/records_sdk/_runtime.py) driven by the operation
// table's `x-records-*` extensions, so both languages behave the same.

type Schema = Record<string, any>;
type Doc = { paths: Record<string, Record<string, any>>; components: { schemas: Record<string, Schema>; parameters: Record<string, any> }; info: { version: string } };

export type Operation = {
  id: string;
  method: string;
  /** Path with `{datastoreId}` and other placeholders. */
  path: string;
  summary: string;
  pathParams: string[];
  query: { name: string; schema: Schema; description?: string }[];
  body: string | null;
  response: string | null;
  idempotency: "safe" | "key" | "natural";
  ifMatch: boolean;
  pagination: Record<string, string> | null;
};

const HEADER = "Generated by packages/records-sdk/scripts/generate.ts from the Records OpenAPI document. Do not edit.";

export function operations(doc: Doc): Operation[] {
  const out: Operation[] = [];
  for (const [path, item] of Object.entries(doc.paths)) {
    for (const [method, op] of Object.entries(item)) {
      if (op["x-records-sdk"] === false) continue;
      const params = (op.parameters ?? []).map((p: any) => (p.$ref ? doc.components.parameters[p.$ref.split("/").pop()] : p));
      const success = Object.entries(op.responses as Record<string, any>).find(([s]) => s.startsWith("2"))?.[1];
      const responseRef: string | undefined = success?.content?.["application/json"]?.schema?.$ref;
      const bodyRef: string | undefined = op.requestBody?.content?.["application/json"]?.schema?.$ref;
      out.push({
        id: op.operationId,
        method: method.toUpperCase(),
        path,
        summary: op.summary ?? "",
        pathParams: params.filter((p: any) => p.in === "path" && p.name !== "datastoreId").map((p: any) => p.name),
        query: params.filter((p: any) => p.in === "query").map((p: any) => ({ name: p.name, schema: p.schema, ...(p.description ? { description: p.description } : {}) })),
        body: bodyRef ? bodyRef.split("/").pop()! : null,
        response: responseRef ? responseRef.split("/").pop()! : null,
        idempotency: op["x-records-idempotency"],
        ifMatch: op["x-records-if-match"] === true,
        pagination: op["x-records-pagination"] ?? null,
      });
    }
  }
  return out;
}

const pascal = (s: string) => s[0]!.toUpperCase() + s.slice(1);
const snake = (s: string) => s.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`);
const iteratorName = (id: string) => `iterate${id.replace(/^list/, "")}`;

// ---------------------------------------------------------------------------------------------
// TypeScript

function tsType(schema: Schema | undefined, indent = ""): string {
  if (!schema || Object.keys(schema).filter((k) => !["description", "default"].includes(k)).length === 0) return "unknown";
  if (schema.$ref) return schema.$ref.split("/").pop();
  if (schema.anyOf || schema.oneOf) return (schema.anyOf ?? schema.oneOf).map((s: Schema) => tsType(s, indent)).join(" | ");
  if ("const" in schema) return JSON.stringify(schema.const);
  if (schema.enum) return schema.enum.map((v: unknown) => JSON.stringify(v)).join(" | ");
  if (Array.isArray(schema.type)) return schema.type.map((t: string) => tsType({ ...schema, type: t }, indent)).join(" | ");
  switch (schema.type) {
    case "string": return "string";
    case "integer":
    case "number": return "number";
    case "boolean": return "boolean";
    case "null": return "null";
    case "array": {
      const item = tsType(schema.items, indent);
      return /[ |]/.test(item) ? `Array<${item}>` : `${item}[]`;
    }
    case "object": {
      const props = Object.entries((schema.properties ?? {}) as Record<string, Schema>);
      const extra = schema.additionalProperties && schema.additionalProperties !== true ? tsType(schema.additionalProperties, indent) : schema.additionalProperties === false ? null : "unknown";
      if (props.length === 0) return `Record<string, ${extra ?? "never"}>`;
      const required = new Set<string>(schema.required ?? []);
      const inner = `${indent}  `;
      const lines = props.map(([name, s]) => `${doc(s.description, inner)}${inner}${/^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name)}${required.has(name) ? "" : "?"}: ${tsType(s, inner)};`);
      return `{\n${lines.join("\n")}\n${indent}}`;
    }
    default: return "unknown";
  }
}

function doc(text: string | undefined, indent: string): string {
  return text ? `${indent}/** ${text.replaceAll("*/", "*\\/").replaceAll("\n", " ")} */\n` : "";
}

export function generateTsTypes(document: Doc): string {
  const lines = [`// ${HEADER}`, ""];
  for (const [name, schema] of Object.entries(document.components.schemas)) {
    lines.push(`${doc(schema.description, "")}export type ${name} = ${tsType(schema)};`, "");
  }
  for (const op of operations(document).filter((o) => o.query.length)) {
    const props = op.query.map((q) => `${doc(q.description, "  ")}  ${q.name}?: ${tsType(q.schema, "  ")};`);
    lines.push(`/** Query parameters of \`${op.id}\`. */`, `export type ${pascal(op.id)}Query = {\n${props.join("\n")}\n};`, "");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

export function generateTsClient(document: Doc): string {
  const ops = operations(document);
  const imports = new Set<string>();
  for (const op of ops) {
    if (op.body) imports.add(op.body);
    if (op.response) imports.add(op.response);
    if (op.query.length) imports.add(`${pascal(op.id)}Query`);
  }
  const table = ops.map((op) => `  ${op.id}: ${JSON.stringify({
    method: op.method, path: op.path, idempotency: op.idempotency, ifMatch: op.ifMatch, pagination: op.pagination,
  })},`);
  const methods: string[] = [];
  for (const op of ops) {
    const params: string[] = op.pathParams.map((p) => `${p}: string`);
    if (op.query.length) params.push(`query: ${pascal(op.id)}Query = {}`);
    if (op.body) params.push(`body: ${op.body}`);
    const optionsType = op.ifMatch ? "WriteOptions & { ifMatch: IfMatch }" : op.idempotency === "key" ? "WriteOptions" : "CallOptions";
    params.push(op.ifMatch ? `options: ${optionsType}` : `options: ${optionsType} = {}`);
    const result = op.response ?? "unknown";
    const pathArg = op.pathParams.length ? `{ ${op.pathParams.join(", ")} }` : "{}";
    methods.push(
      `  /** ${op.summary}. \`${op.method} ${op.path.replace("/gatekeeper/records/v1", "")}\` */`,
      `  ${op.id}(${params.join(", ")}): Promise<${result}> {`,
      `    return this.call<${result}>(OPERATIONS.${op.id}, ${pathArg}, ${op.query.length ? "query" : "undefined"}, ${op.body ? "body" : "undefined"}, options);`,
      "  }",
      "",
    );
    if (op.pagination && op.response) {
      const page = document.components.schemas[op.response]!;
      const itemsField = op.pagination.itemsField!;
      const itemRef: string | undefined = page.properties?.[itemsField]?.items?.$ref;
      const item = itemRef ? itemRef.split("/").pop()! : "unknown";
      if (itemRef) imports.add(item);
      const iterParams = [...op.pathParams.map((p) => `${p}: string`), `query: ${pascal(op.id)}Query = {}`, "options: CallOptions = {}"];
      const cursorName = op.pagination.style === "cursor" ? op.pagination.cursorParam : op.pagination.afterParam;
      methods.push(
        op.pagination.style === "cursor"
          ? `  /** Every item of \`${op.id}\`, following \`${op.pagination.nextField}\` page by page. */`
          : `  /** Every entry of \`${op.id}\` after \`query.${cursorName}\` up to the head at the time of each page. */`,
        `  ${iteratorName(op.id)}(${iterParams.join(", ")}): AsyncGenerator<${item}> {`,
        `    return this.paginate<${item}>(OPERATIONS.${op.id}, ${pathArg}, query, options);`,
        "  }",
        "",
      );
    }
  }
  return [
    `// ${HEADER}`,
    "",
    `import { BaseClient, type CallOptions, type IfMatch, type OperationSpec, type WriteOptions } from "../runtime.js";`,
    `import type { ${[...imports].sort().join(", ")} } from "./types.js";`,
    "",
    `/** The API version this client was generated from. */`,
    `export const API_VERSION = ${JSON.stringify(document.info.version)};`,
    "",
    "export const OPERATIONS = {",
    ...table,
    "} as const satisfies Record<string, OperationSpec>;",
    "",
    "/** Typed client for the Records native API, bound to one datastore. */",
    "export class RecordsClient extends BaseClient {",
    ...methods,
    "}",
    "",
  ].join("\n").replace(/\n\n}\n$/, "\n}\n");
}

// ---------------------------------------------------------------------------------------------
// Python

function pyType(schema: Schema | undefined): string {
  if (!schema || Object.keys(schema).filter((k) => !["description", "default"].includes(k)).length === 0) return "Any";
  if (schema.$ref) return `"${schema.$ref.split("/").pop()}"`;
  if (schema.anyOf || schema.oneOf) {
    const parts = [...new Set<string>((schema.anyOf ?? schema.oneOf).map((s: Schema) => pyType(s)))];
    return parts.length === 1 ? parts[0]! : `Union[${parts.join(", ")}]`;
  }
  if ("const" in schema) return `Literal[${JSON.stringify(schema.const)}]`;
  if (schema.enum) return `Literal[${schema.enum.map((v: unknown) => JSON.stringify(v)).join(", ")}]`;
  switch (schema.type) {
    case "string": return "str";
    case "integer": return "int";
    case "number": return "float";
    case "boolean": return "bool";
    case "null": return "None";
    case "array": return `List[${pyType(schema.items)}]`;
    case "object": return schema.properties ? "Dict[str, Any]" : `Dict[str, ${schema.additionalProperties && schema.additionalProperties !== true ? pyType(schema.additionalProperties) : "Any"}]`;
    default: return "Any";
  }
}

const PY_KEYWORDS = new Set(["from", "to", "in", "is", "not", "and", "or", "class", "def", "return", "global", "type", "id"]);

export function generatePython(document: Doc): string {
  const out: string[] = [
    `# ${HEADER}`,
    "# ruff: noqa",
    "from __future__ import annotations",
    "",
    "from typing import Any, Dict, Iterator, List, Literal, NotRequired, Optional, TypedDict, Union",
    "",
    "from ._runtime import BaseClient, IfMatch",
    "",
    `API_VERSION = ${JSON.stringify(document.info.version)}`,
    "",
  ];
  // Component types: TypedDicts for objects with properties (functional syntax: field names such
  // as `from` are Python keywords), aliases for the rest.
  for (const [name, schema] of Object.entries(document.components.schemas)) {
    if (schema.type === "object" && schema.properties) {
      const required = new Set<string>(schema.required ?? []);
      const fields = Object.entries(schema.properties as Record<string, Schema>).map(([k, s]) => {
        const t = pyType(s);
        return `    ${JSON.stringify(k)}: ${required.has(k) ? t : `NotRequired[${t}]`},`;
      });
      out.push(`${name} = TypedDict(${JSON.stringify(name)}, {`, ...fields, "})", "");
    } else {
      out.push(`${name} = ${pyType(schema).replace(/^"(.*)"$/, "$1")}`, "");
    }
  }
  const ops = operations(document);
  out.push("OPERATIONS: Dict[str, Dict[str, Any]] = {");
  for (const op of ops) {
    out.push(`    ${JSON.stringify(op.id)}: ${JSON.stringify({ method: op.method, path: op.path, idempotency: op.idempotency, ifMatch: op.ifMatch, pagination: op.pagination })
      .replaceAll(":true", ":True").replaceAll(":false", ":False").replaceAll(":null", ":None")},`);
  }
  out.push("}", "", "", "class RecordsClient(BaseClient):", '    """Typed client for the Records native API, bound to one datastore."""', "");
  for (const op of ops) {
    const args = ["self", ...op.pathParams.map((p) => `${snake(p)}: str`)];
    if (op.body) args.push(`body: ${op.body}`);
    const kw: string[] = [];
    for (const q of op.query) kw.push(`${pyQueryName(q.name)}: Optional[${pyType(q.schema).replace(/^"(.*)"$/, "$1")}] = None`);
    if (op.ifMatch) kw.push("if_match: IfMatch");
    if (op.idempotency === "key") kw.push("idempotency_key: Optional[str] = None");
    const signature = kw.length ? [...args, "*", ...kw] : args;
    const queryDict = op.query.length ? `{${op.query.map((q) => `${JSON.stringify(q.name)}: ${pyQueryName(q.name)}`).join(", ")}}` : "None";
    const pathDict = `{${op.pathParams.map((p) => `${JSON.stringify(p)}: ${snake(p)}`).join(", ")}}`;
    const result = op.response ?? "Any";
    out.push(
      `    def ${snake(op.id)}(${signature.join(", ")}) -> ${result}:`,
      `        """${op.summary}."""`,
      `        return self._call(OPERATIONS[${JSON.stringify(op.id)}], ${pathDict}, ${queryDict}, ${op.body ? "body" : "None"}, ` +
        `if_match=${op.ifMatch ? "if_match" : "None"}, idempotency_key=${op.idempotency === "key" ? "idempotency_key" : "None"})`,
      "",
    );
    if (op.pagination && op.response) {
      const itemRef: string | undefined = document.components.schemas[op.response]!.properties?.[op.pagination.itemsField!]?.items?.$ref;
      const item = itemRef ? itemRef.split("/").pop()! : "Any";
      const iterArgs = [...args.filter((a) => !a.startsWith("body")), ...(op.query.length ? ["*", ...op.query.map((q) => `${pyQueryName(q.name)}: Optional[${pyType(q.schema).replace(/^"(.*)"$/, "$1")}] = None`)] : [])];
      out.push(
        `    def ${snake(iteratorName(op.id))}(${iterArgs.join(", ")}) -> Iterator[${item}]:`,
        `        """Every item of ${snake(op.id)}, page by page."""`,
        `        return self._paginate(OPERATIONS[${JSON.stringify(op.id)}], ${pathDict}, ${queryDict})`,
        "",
      );
    }
  }
  return `${out.join("\n").trimEnd()}\n`;
}

function pyQueryName(name: string): string {
  const s = snake(name);
  return PY_KEYWORDS.has(s) ? `${s}_` : s;
}
