import css from './style.css'

const style = document.createElement('style'); style.textContent = css; document.head.append(style)
document.body.innerHTML = '<main id="root"><section class="empty"><h2>Opening Synthetic Data Explorer…</h2></section></main>'
const root = document.querySelector('#root')
let dataset, collections = [], schema, page, aggregate, state = { cursorHistory: [] }, mode = 'rows', busy = false, errorMessage = '', inspected = null
const el = (tag, className, text) => { const node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node }
const button = (label, action, className = 'quiet') => { const node = el('button', className, label); node.type = 'button'; node.onclick = () => safe(action)(); return node }
const safe = handler => (...args) => Promise.resolve().then(() => handler(...args)).catch(error => { errorMessage = error?.message || String(error); render() })
const display = value => value === null ? 'null' : typeof value === 'object' ? JSON.stringify(value) : String(value)
const prettyCount = count => { try { return Intl.NumberFormat().format(BigInt(count)) } catch { return String(count) } }
const currentCollection = () => collections.find(item => item.name === state.collection)
async function persist() { state = await gadget.setState(state) }
async function selectCollection(name) { state = { collection: name, cursorHistory: [] }; inspected = null; aggregate = null; mode = 'rows'; await persist(); await loadCollection() }
async function loadCollection() { busy = true; errorMessage = ''; render(); schema = await gadget.describeCollection(state.collection); const fields = schema.fields.slice(0, 8).map(field => field.name); state.query = { collection: state.collection, limit: 50, fields }; await runQuery(false) }
async function runQuery(keepResults = true) { busy = true; errorMessage = ''; if (!keepResults) page = null; render(); page = await gadget.query(state.query); busy = false; await persist(); render() }
async function next() { if (!page?.nextCursor) return; state.cursorHistory.push(state.query.cursor || ''); state.query = { ...state.query, cursor: page.nextCursor }; await runQuery() }
async function previous() { if (!state.cursorHistory.length) return; const cursor = state.cursorHistory.pop(); state.query = { ...state.query, ...(cursor ? { cursor } : {}) }; if (!cursor) delete state.query.cursor; await runQuery() }
async function inspect(collection, id) { inspected = { collection, id, record: await gadget.getRecord(collection, id), schema: collection === schema.name ? schema : await gadget.describeCollection(collection) }; state.selectedRecordId = id; await persist(); render() }
async function applyFilter(field, operator, raw) { const fieldSchema = schema.fields.find(item => item.name === field); let value = raw; if (fieldSchema?.type === 'number') value = Number(raw); if (fieldSchema?.type === 'boolean') value = raw === 'true'; state.cursorHistory = []; state.query = { ...state.query, predicates: raw === '' ? [] : [{ field, operator, value }] }; delete state.query.cursor; await runQuery() }
async function runAggregate(shape, groupBy) { const metric = shape.functions.includes('count') ? 'count' : shape.functions[0]; const request = { collection: schema.name, metrics: [{ name: `${metric}_${shape.field || 'records'}`, function: metric, ...(shape.field ? { field: shape.field } : {}) }], ...(groupBy ? { groupBy: [groupBy] } : {}), limitGroups: 100 }; state.aggregate = request; busy = true; errorMessage = ''; render(); aggregate = await gadget.aggregate(request); busy = false; await persist(); render() }
function render() {
  root.replaceChildren(); root.className = dataset ? 'app' : ''
  if (!dataset) { const box = el('section', errorMessage ? 'failure' : 'empty'); box.append(el('h2', '', errorMessage ? 'Connect Synthetic Data' : 'Opening explorer…'), el('p', '', errorMessage || 'Loading the connected dataset.')); if (errorMessage) box.append(button('Retry', initialize, 'primary')); root.append(box); return }
  const header = el('header', 'dataset'); header.append(el('div', 'mark', 'Data Explorer'))
  const meta = el('div', 'meta'); for (const [label, value] of [['Scenario', dataset.scenario], ['Version', dataset.version], ['Seed', dataset.seedLabel], ['Size', dataset.sizeProfile]]) { const item = el('span'); item.append(el('strong', '', label + ' '), document.createTextNode(value)); meta.append(item) } header.append(meta, el('div', 'status', 'Generated on demand')); root.append(header)
  const rail = el('nav', 'rail'); rail.setAttribute('aria-label', 'Collections'); rail.append(el('div', 'eyebrow', 'Collections')); for (const item of collections) { const choice = el('button', `collection${item.name === state.collection ? ' active' : ''}`); choice.append(el('strong', '', item.title || item.name), el('span', '', `${prettyCount(item.exactRecords)} records`)); choice.onclick = () => safe(() => selectCollection(item.name))(); rail.append(choice) } root.append(rail)
  const work = el('section', 'workspace'); const topline = el('div', 'topline'); const title = el('div'); title.append(el('h1', '', currentCollection()?.title || state.collection), el('p', '', schema ? `${prettyCount(schema.exactRecords)} records · ${schema.fields.length} fields` : 'Loading schema…')); const tabs = el('div', 'tabs'); for (const value of ['rows', 'metrics']) { const tab = button(value === 'rows' ? 'Rows' : 'Exact metrics', () => { mode = value; render() }, value === mode ? 'active' : ''); tab.setAttribute('aria-pressed', String(value === mode)); tabs.append(tab) } topline.append(title, tabs); work.append(topline)
  if (errorMessage) work.append(el('div', 'notice', errorMessage))
  const panel = el('div', 'panel'); if (!schema) panel.append(el('div', 'empty', 'Loading…')); else if (mode === 'rows') renderRows(panel); else renderMetrics(panel); work.append(panel); root.append(work)
  if (inspected) renderInspector(root)
}
function renderRows(panel) {
  const controls = el('form', 'controls'); controls.onsubmit = event => { event.preventDefault(); const data = new FormData(controls); safe(() => applyFilter(data.get('field'), data.get('operator'), data.get('value')))() }
  const indexes = schema.indexes.flatMap(index => index.fields.map(field => ({ field, operators: index.operators }))); if (indexes.length) { const field = selectControl('Field', 'field', indexes.map(item => item.field)); const operator = selectControl('Operator', 'operator', indexes[0].operators); field.querySelector('select').onchange = event => { const found = indexes.find(item => item.field === event.target.value); fillSelect(operator.querySelector('select'), found?.operators || []) }; const value = el('div', 'control'); value.append(el('label', '', 'Value')); const input = el('input'); input.name = 'value'; input.setAttribute('aria-label', 'Filter value'); value.append(input); controls.append(field, operator, value, submit('Apply filter'), button('Clear', async () => { state.query.predicates = []; state.cursorHistory = []; delete state.query.cursor; await runQuery() })) } else controls.append(el('span', '', 'This collection advertises no indexed filters.'))
  panel.append(controls); if (!page?.records?.length) { const empty = el('div', 'empty'); empty.append(el('h2', '', busy ? 'Loading records…' : 'No matching records'), el('p', '', busy ? 'The current results stay visible while later pages load.' : 'Clear the filter or choose another collection.')); panel.append(empty); return }
  const fields = page.schema.fields.filter(field => state.query.fields?.includes(field.name)); const wrap = el('div', 'table-wrap'); const table = el('table'); const caption = el('caption', 'sr', `${schema.title} records`); const head = el('tr'); fields.forEach(field => head.append(el('th', '', field.name))); table.append(caption, el('thead')); table.tHead.append(head); const body = el('tbody'); for (const record of page.records) { const row = el('tr'); for (const field of fields) { const cell = el('td'); const value = record[field.name]; if (field.references && typeof value === 'string') cell.append(button(display(value), () => inspect(field.references.collection, value), 'link')); else if (field.name === schema.primaryKey && typeof value === 'string') cell.append(button(display(value), () => inspect(schema.name, value), 'link')); else cell.textContent = display(value); cell.title = display(value); row.append(cell) } body.append(row) } table.append(body); wrap.append(table); panel.append(wrap)
  const pager = el('div', 'pager'); pager.append(el('span', '', `${page.records.length} records`), button('Previous', previous), button(busy ? 'Loading…' : 'Next', next, 'primary')); pager.children[1].disabled = !state.cursorHistory.length || busy; pager.children[2].disabled = !page.nextCursor || busy; panel.append(pager)
}
function renderMetrics(panel) {
  const controls = el('div', 'controls'); if (!schema.aggregates.length) controls.append(el('span', '', 'This collection advertises no exact aggregates.')); else { schema.aggregates.forEach((shape, index) => { const label = `${shape.functions.join(' / ')}${shape.field ? ` · ${shape.field}` : ''}`; const groups = shape.groupBy || []; const group = groups[0]; controls.append(button(`${label}${group ? ` by ${group}` : ''}`, () => runAggregate(shape, group), index === 0 ? 'primary' : 'quiet')) }) } panel.append(controls)
  if (!aggregate) { const empty = el('div', 'empty'); empty.append(el('h2', '', busy ? 'Calculating exact metrics…' : 'Choose an advertised metric'), el('p', '', 'Only bounded aggregate shapes supplied by the dataset are available. Results are exact, never estimates.')); panel.append(empty); return }
  const keys = Object.keys(aggregate.groups[0]?.key || {}), metrics = Object.keys(aggregate.groups[0]?.metrics || {}); const wrap = el('div', 'table-wrap'), table = el('table'), head = el('tr'); [...keys, ...metrics].forEach(item => head.append(el('th', '', item))); head.append(el('th', '', 'Accuracy')); const thead = el('thead'); thead.append(head); const body = el('tbody'); aggregate.groups.forEach(group => { const row = el('tr'); keys.forEach(key => row.append(el('td', '', display(group.key[key])))); metrics.forEach(key => row.append(el('td', '', display(group.metrics[key])))); row.append(el('td', '', 'Exact')); body.append(row) }); table.append(thead, body); wrap.append(table); panel.append(wrap)
}
function renderInspector(parent) { const aside = el('aside', 'inspector'); const header = el('header'); const heading = el('div'); heading.append(el('div', 'eyebrow', inspected.collection), el('h2', '', inspected.id)); const close = button('Close', async () => { inspected = null; delete state.selectedRecordId; await persist(); render() }); header.append(heading, close); aside.append(header); const list = el('dl'); for (const field of inspected.schema.fields) { list.append(el('dt', '', field.name)); const value = inspected.record?.[field.name]; const definition = el('dd'); if (field.references && typeof value === 'string') definition.append(button(display(value), () => inspect(field.references.collection, value), 'link')); else definition.textContent = display(value); list.append(definition) } aside.append(list, el('h3', '', 'JSON')); const raw = JSON.stringify(inspected.record, null, 2); aside.append(el('pre', '', raw.length > 20_000 ? raw.slice(0, 20_000) + '\n… truncated' : raw)); parent.append(aside); close.focus() }
function selectControl(label, name, values) { const wrapper = el('div', 'control'); wrapper.append(el('label', '', label)); const select = el('select'); select.name = name; select.setAttribute('aria-label', label); fillSelect(select, [...new Set(values)]); wrapper.append(select); return wrapper }
function fillSelect(select, values) { select.replaceChildren(...values.map(value => { const option = el('option', '', value); option.value = value; return option })) }
function submit(label) { const node = el('button', 'primary', label); node.type = 'submit'; return node }
async function initialize() { errorMessage = ''; render(); [dataset, collections, state] = await Promise.all([gadget.describeDataset(), gadget.listCollections(), gadget.getState()]); if (!state.collection || !collections.some(item => item.name === state.collection)) state = { collection: collections[0]?.name, cursorHistory: [] }; if (!state.collection) throw new Error('The connected dataset has no collections.'); await loadCollection() }
await safe(initialize)()
