// @records/sdk: a typed client for the Records native API, generated from its OpenAPI document
// (scripts/generate.ts). The Python SDK, generated by the same script, is in ./python.
export { API_VERSION, OPERATIONS, RecordsClient } from "./generated/client.js";
export type * from "./generated/types.js";
export {
  RecordsApiError,
  RecordsNetworkError,
  RevisionConflictError,
  retryAfterMs,
  revisionOf,
  type CallOptions,
  type IfMatch,
  type OperationSpec,
  type Problem,
  type RecordsClientOptions,
  type RetryPolicy,
  type WriteOptions,
} from "./runtime.js";
