# Generated by packages/records-sdk/scripts/generate.ts from the Records OpenAPI document. Do not edit.
# ruff: noqa
from __future__ import annotations

from typing import Any, Dict, Iterator, List, Literal, NotRequired, Optional, TypedDict, Union

from ._runtime import BaseClient, IfMatch

API_VERSION = "1.0.0"

PrincipalRef = TypedDict("PrincipalRef", {
    "id": str,
    "displayName": str,
    "kind": Literal["human", "service"],
})

Datastore = Dict[str, Any]

Project = TypedDict("Project", {
    "id": str,
    "key": str,
    "name": str,
    "description": str,
    "revision": int,
    "createdAt": str,
    "updatedAt": str,
})

ProjectList = TypedDict("ProjectList", {
    "items": List["Project"],
})

Workflow = TypedDict("Workflow", {
    "states": List[Dict[str, Any]],
    "transitions": List[Dict[str, Any]],
})

Issue = TypedDict("Issue", {
    "id": str,
    "projectId": str,
    "number": int,
    "key": str,
    "title": str,
    "description": str,
    "state": str,
    "priority": Literal["none", "low", "medium", "high", "urgent"],
    "assignee": Union["PrincipalRef", None],
    "customFields": Dict[str, Union[str, float, bool, None]],
    "revision": int,
    "createdAt": str,
    "updatedAt": str,
    "createdBy": "PrincipalRef",
    "updatedBy": "PrincipalRef",
})

IssuePage = TypedDict("IssuePage", {
    "items": List["Issue"],
    "nextCursor": Union[str, None],
})

Comment = TypedDict("Comment", {
    "id": str,
    "issueId": str,
    "body": str,
    "author": "PrincipalRef",
    "createdAt": str,
})

CommentPage = TypedDict("CommentPage", {
    "items": List["Comment"],
    "nextCursor": Union[str, None],
})

AuditEvent = TypedDict("AuditEvent", {
    "id": str,
    "datastoreId": Union[str, None],
    "operation": str,
    "actor": "PrincipalRef",
    "initiator": Union["PrincipalRef", None],
    "bindingId": Union[str, None],
    "via": Literal["gadget", "http", "management", "system"],
    "targetType": Union[str, None],
    "targetId": Union[str, None],
    "summary": str,
    "at": str,
})

AuditPage = TypedDict("AuditPage", {
    "items": List["AuditEvent"],
    "nextCursor": Union[str, None],
})

JournalEntry = TypedDict("JournalEntry", {
    "seq": int,
    "ordinal": int,
    "changeId": str,
    "command": str,
    "entityType": Literal["project", "issue", "comment"],
    "entityId": str,
    "entityRev": int,
    "op": Literal["create", "update", "archive", "restore", "redact"],
    "after": Dict[str, Any],
    "before": Union[Dict[str, Any], None],
    "actorId": str,
    "actId": Union[str, None],
    "via": Literal["gadget", "http", "sync", "jira", "management", "system"],
    "occurredAt": str,
})

History = TypedDict("History", {
    "items": List["JournalEntry"],
})

ChangesPage = TypedDict("ChangesPage", {
    "entries": List["JournalEntry"],
    "nextAfter": int,
    "head": int,
    "resetRequired": bool,
})

PushOutcome = Dict[str, Any]

PushResponse = TypedDict("PushResponse", {
    "outcomes": List["PushOutcome"],
    "head": int,
})

PatchOp = Dict[str, Any]

PullResponse = TypedDict("PullResponse", {
    "cookie": int,
    "lastMutationIdChanges": Dict[str, int],
    "patch": List["PatchOp"],
})

Problem = TypedDict("Problem", {
    "type": str,
    "title": str,
    "status": int,
    "code": Literal["unauthenticated", "forbidden", "not_found", "validation_failed", "revision_conflict", "revision_required", "workflow_conflict", "idempotency_conflict", "datastore_archived", "duplicate", "payload_too_large", "rate_limited", "unavailable", "internal"],
    "detail": NotRequired[str],
    "issues": NotRequired[List[Dict[str, Any]]],
})

CreateIssueRequest = TypedDict("CreateIssueRequest", {
    "id": NotRequired[str],
    "projectId": str,
    "title": str,
    "description": NotRequired[str],
    "state": NotRequired[str],
    "priority": NotRequired[Literal["none", "low", "medium", "high", "urgent"]],
    "assigneeId": NotRequired[Union[str, None]],
    "customFields": NotRequired[Dict[str, Union[str, float, bool, None]]],
})

EditIssueRequest = TypedDict("EditIssueRequest", {
    "title": NotRequired[str],
    "description": NotRequired[str],
    "priority": NotRequired[Literal["none", "low", "medium", "high", "urgent"]],
    "assigneeId": NotRequired[Union[str, None]],
    "customFields": NotRequired[Dict[str, Union[str, float, bool, None]]],
})

TransitionIssueRequest = TypedDict("TransitionIssueRequest", {
    "toState": str,
})

AddCommentRequest = TypedDict("AddCommentRequest", {
    "body": str,
})

PushRequest = TypedDict("PushRequest", {
    "clientGroupId": str,
    "clientId": str,
    "mutations": List[Dict[str, Any]],
})

PullRequest = TypedDict("PullRequest", {
    "clientGroupId": str,
    "cookie": Union[int, None],
})

OPERATIONS: Dict[str, Dict[str, Any]] = {
    "getDatastore": {"method":"GET","path":"/gatekeeper/records/v1/datastores/{datastoreId}","idempotency":"safe","ifMatch":False,"pagination":None},
    "listProjects": {"method":"GET","path":"/gatekeeper/records/v1/datastores/{datastoreId}/projects","idempotency":"safe","ifMatch":False,"pagination":None},
    "getWorkflow": {"method":"GET","path":"/gatekeeper/records/v1/datastores/{datastoreId}/workflow","idempotency":"safe","ifMatch":False,"pagination":None},
    "listIssues": {"method":"GET","path":"/gatekeeper/records/v1/datastores/{datastoreId}/issues","idempotency":"safe","ifMatch":False,"pagination":{"style":"cursor","cursorParam":"cursor","nextField":"nextCursor","itemsField":"items"}},
    "createIssue": {"method":"POST","path":"/gatekeeper/records/v1/datastores/{datastoreId}/issues","idempotency":"key","ifMatch":False,"pagination":None},
    "getIssue": {"method":"GET","path":"/gatekeeper/records/v1/datastores/{datastoreId}/issues/{issueId}","idempotency":"safe","ifMatch":False,"pagination":None},
    "editIssue": {"method":"PATCH","path":"/gatekeeper/records/v1/datastores/{datastoreId}/issues/{issueId}","idempotency":"key","ifMatch":True,"pagination":None},
    "transitionIssue": {"method":"POST","path":"/gatekeeper/records/v1/datastores/{datastoreId}/issues/{issueId}/transitions","idempotency":"key","ifMatch":True,"pagination":None},
    "listComments": {"method":"GET","path":"/gatekeeper/records/v1/datastores/{datastoreId}/issues/{issueId}/comments","idempotency":"safe","ifMatch":False,"pagination":{"style":"cursor","cursorParam":"cursor","nextField":"nextCursor","itemsField":"items"}},
    "addComment": {"method":"POST","path":"/gatekeeper/records/v1/datastores/{datastoreId}/issues/{issueId}/comments","idempotency":"key","ifMatch":False,"pagination":None},
    "getIssueHistory": {"method":"GET","path":"/gatekeeper/records/v1/datastores/{datastoreId}/issues/{issueId}/history","idempotency":"safe","ifMatch":False,"pagination":None},
    "listChanges": {"method":"GET","path":"/gatekeeper/records/v1/datastores/{datastoreId}/changes","idempotency":"safe","ifMatch":False,"pagination":{"style":"seq","afterParam":"after","nextField":"nextAfter","itemsField":"entries","headField":"head"}},
    "syncPush": {"method":"POST","path":"/gatekeeper/records/v1/datastores/{datastoreId}/sync/push","idempotency":"natural","ifMatch":False,"pagination":None},
    "syncPull": {"method":"POST","path":"/gatekeeper/records/v1/datastores/{datastoreId}/sync/pull","idempotency":"safe","ifMatch":False,"pagination":None},
    "listAudit": {"method":"GET","path":"/gatekeeper/records/v1/datastores/{datastoreId}/audit","idempotency":"safe","ifMatch":False,"pagination":{"style":"cursor","cursorParam":"cursor","nextField":"nextCursor","itemsField":"items"}},
}


class RecordsClient(BaseClient):
    """Typed client for the Records native API, bound to one datastore."""

    def get_datastore(self) -> Datastore:
        """The datastore the credential is bound to."""
        return self._call(OPERATIONS["getDatastore"], {}, None, None, if_match=None, idempotency_key=None)

    def list_projects(self) -> ProjectList:
        """List projects."""
        return self._call(OPERATIONS["listProjects"], {}, None, None, if_match=None, idempotency_key=None)

    def get_workflow(self) -> Workflow:
        """The workflow states and allowed transitions."""
        return self._call(OPERATIONS["getWorkflow"], {}, None, None, if_match=None, idempotency_key=None)

    def list_issues(self, *, project_id: Optional[str] = None, state: Optional[str] = None, assignee_id: Optional[str] = None, q: Optional[str] = None, order: Optional[Literal["updated_desc", "number_asc"]] = None, limit: Optional[int] = None, cursor: Optional[str] = None) -> IssuePage:
        """Search issues."""
        return self._call(OPERATIONS["listIssues"], {}, {"projectId": project_id, "state": state, "assigneeId": assignee_id, "q": q, "order": order, "limit": limit, "cursor": cursor}, None, if_match=None, idempotency_key=None)

    def iterate_issues(self, *, project_id: Optional[str] = None, state: Optional[str] = None, assignee_id: Optional[str] = None, q: Optional[str] = None, order: Optional[Literal["updated_desc", "number_asc"]] = None, limit: Optional[int] = None, cursor: Optional[str] = None) -> Iterator[Issue]:
        """Every item of list_issues, page by page."""
        return self._paginate(OPERATIONS["listIssues"], {}, {"projectId": project_id, "state": state, "assigneeId": assignee_id, "q": q, "order": order, "limit": limit, "cursor": cursor})

    def create_issue(self, body: CreateIssueRequest, *, idempotency_key: Optional[str] = None) -> Issue:
        """Create an issue."""
        return self._call(OPERATIONS["createIssue"], {}, None, body, if_match=None, idempotency_key=idempotency_key)

    def get_issue(self, issue_id: str) -> Issue:
        """Get an issue."""
        return self._call(OPERATIONS["getIssue"], {"issueId": issue_id}, None, None, if_match=None, idempotency_key=None)

    def edit_issue(self, issue_id: str, body: EditIssueRequest, *, if_match: IfMatch, idempotency_key: Optional[str] = None) -> Issue:
        """Edit an issue's fields."""
        return self._call(OPERATIONS["editIssue"], {"issueId": issue_id}, None, body, if_match=if_match, idempotency_key=idempotency_key)

    def transition_issue(self, issue_id: str, body: TransitionIssueRequest, *, if_match: IfMatch, idempotency_key: Optional[str] = None) -> Issue:
        """Move an issue to another workflow state."""
        return self._call(OPERATIONS["transitionIssue"], {"issueId": issue_id}, None, body, if_match=if_match, idempotency_key=idempotency_key)

    def list_comments(self, issue_id: str, *, limit: Optional[int] = None, cursor: Optional[str] = None) -> CommentPage:
        """List an issue's comments."""
        return self._call(OPERATIONS["listComments"], {"issueId": issue_id}, {"limit": limit, "cursor": cursor}, None, if_match=None, idempotency_key=None)

    def iterate_comments(self, issue_id: str, *, limit: Optional[int] = None, cursor: Optional[str] = None) -> Iterator[Comment]:
        """Every item of list_comments, page by page."""
        return self._paginate(OPERATIONS["listComments"], {"issueId": issue_id}, {"limit": limit, "cursor": cursor})

    def add_comment(self, issue_id: str, body: AddCommentRequest, *, idempotency_key: Optional[str] = None) -> Comment:
        """Comment on an issue."""
        return self._call(OPERATIONS["addComment"], {"issueId": issue_id}, None, body, if_match=None, idempotency_key=idempotency_key)

    def get_issue_history(self, issue_id: str) -> History:
        """An issue's journal entries."""
        return self._call(OPERATIONS["getIssueHistory"], {"issueId": issue_id}, None, None, if_match=None, idempotency_key=None)

    def list_changes(self, *, after: Optional[int] = None, limit: Optional[int] = None) -> ChangesPage:
        """The commit-ordered journal after a sequence number."""
        return self._call(OPERATIONS["listChanges"], {}, {"after": after, "limit": limit}, None, if_match=None, idempotency_key=None)

    def iterate_changes(self, *, after: Optional[int] = None, limit: Optional[int] = None) -> Iterator[JournalEntry]:
        """Every item of list_changes, page by page."""
        return self._paginate(OPERATIONS["listChanges"], {}, {"after": after, "limit": limit})

    def sync_push(self, body: PushRequest) -> PushResponse:
        """Push client mutations (sync protocol)."""
        return self._call(OPERATIONS["syncPush"], {}, None, body, if_match=None, idempotency_key=None)

    def sync_pull(self, body: PullRequest) -> PullResponse:
        """Pull the patch since a cookie (sync protocol)."""
        return self._call(OPERATIONS["syncPull"], {}, None, body, if_match=None, idempotency_key=None)

    def list_audit(self, *, limit: Optional[int] = None, cursor: Optional[str] = None) -> AuditPage:
        """The datastore's audit log."""
        return self._call(OPERATIONS["listAudit"], {}, {"limit": limit, "cursor": cursor}, None, if_match=None, idempotency_key=None)

    def iterate_audit(self, *, limit: Optional[int] = None, cursor: Optional[str] = None) -> Iterator[AuditEvent]:
        """Every item of list_audit, page by page."""
        return self._paginate(OPERATIONS["listAudit"], {}, {"limit": limit, "cursor": cursor})
