// @ts-check
// Curated Unicode symbols for diagrams (the "Emoji & symbols" tab's non-emoji groups).
// Each entry is [character, Unicode character name, extra search words]. The names are the
// formal names from the Unicode Character Database (UnicodeData.txt, Unicode 16.0.0), copied when
// the table was written; one character appears once. Edit here, then run
// `node scripts/build-icon-packs.mjs` to regenerate src/client/generated/unicode-data.js.

/** @typedef {[string, string, string]} SymbolDecl */

/** @type {{id: string, label: string, symbols: SymbolDecl[]}[]} */
export const SYMBOL_GROUPS = [
  {
    id: "arrows", label: "Arrows", symbols: [
      ["→", "RIGHTWARDS ARROW", "right implies then to next"],
      ["←", "LEFTWARDS ARROW", "left back"],
      ["↑", "UPWARDS ARROW", "up increase"],
      ["↓", "DOWNWARDS ARROW", "down decrease"],
      ["↔", "LEFT RIGHT ARROW", "both ways bidirectional"],
      ["↕", "UP DOWN ARROW", ""],
      ["↖", "NORTH WEST ARROW", ""],
      ["↗", "NORTH EAST ARROW", ""],
      ["↘", "SOUTH EAST ARROW", ""],
      ["↙", "SOUTH WEST ARROW", ""],
      ["⇒", "RIGHTWARDS DOUBLE ARROW", "implies therefore"],
      ["⇐", "LEFTWARDS DOUBLE ARROW", ""],
      ["⇑", "UPWARDS DOUBLE ARROW", ""],
      ["⇓", "DOWNWARDS DOUBLE ARROW", ""],
      ["⇔", "LEFT RIGHT DOUBLE ARROW", "if and only if iff equivalent"],
      ["⇕", "UP DOWN DOUBLE ARROW", ""],
      ["⟶", "LONG RIGHTWARDS ARROW", "long right maps"],
      ["⟵", "LONG LEFTWARDS ARROW", ""],
      ["⟷", "LONG LEFT RIGHT ARROW", ""],
      ["⟹", "LONG RIGHTWARDS DOUBLE ARROW", ""],
      ["⟸", "LONG LEFTWARDS DOUBLE ARROW", ""],
      ["⟺", "LONG LEFT RIGHT DOUBLE ARROW", ""],
      ["↦", "RIGHTWARDS ARROW FROM BAR", ""],
      ["↩", "LEFTWARDS ARROW WITH HOOK", ""],
      ["↪", "RIGHTWARDS ARROW WITH HOOK", ""],
      ["↰", "UPWARDS ARROW WITH TIP LEFTWARDS", ""],
      ["↱", "UPWARDS ARROW WITH TIP RIGHTWARDS", ""],
      ["↲", "DOWNWARDS ARROW WITH TIP LEFTWARDS", ""],
      ["↳", "DOWNWARDS ARROW WITH TIP RIGHTWARDS", ""],
      ["↴", "RIGHTWARDS ARROW WITH CORNER DOWNWARDS", ""],
      ["↺", "ANTICLOCKWISE OPEN CIRCLE ARROW", "undo cycle loop"],
      ["↻", "CLOCKWISE OPEN CIRCLE ARROW", "refresh repeat redo cycle loop"],
      ["⟲", "ANTICLOCKWISE GAPPED CIRCLE ARROW", "undo"],
      ["⟳", "CLOCKWISE GAPPED CIRCLE ARROW", "refresh reload"],
      ["⇄", "RIGHTWARDS ARROW OVER LEFTWARDS ARROW", "swap exchange sync"],
      ["⇆", "LEFTWARDS ARROW OVER RIGHTWARDS ARROW", ""],
      ["⇅", "UPWARDS ARROW LEFTWARDS OF DOWNWARDS ARROW", ""],
      ["⇉", "RIGHTWARDS PAIRED ARROWS", ""],
      ["⇇", "LEFTWARDS PAIRED ARROWS", ""],
      ["⇢", "RIGHTWARDS DASHED ARROW", ""],
      ["⇠", "LEFTWARDS DASHED ARROW", ""],
      ["↝", "RIGHTWARDS WAVE ARROW", ""],
      ["↜", "LEFTWARDS WAVE ARROW", ""],
      ["↯", "DOWNWARDS ZIGZAG ARROW", "lightning zigzag"],
      ["⤴", "ARROW POINTING RIGHTWARDS THEN CURVING UPWARDS", ""],
      ["⤵", "ARROW POINTING RIGHTWARDS THEN CURVING DOWNWARDS", ""],
      ["➔", "HEAVY WIDE-HEADED RIGHTWARDS ARROW", ""],
      ["➜", "HEAVY ROUND-TIPPED RIGHTWARDS ARROW", ""],
      ["➝", "TRIANGLE-HEADED RIGHTWARDS ARROW", ""],
      ["➞", "HEAVY TRIANGLE-HEADED RIGHTWARDS ARROW", ""],
      ["➡", "BLACK RIGHTWARDS ARROW", ""],
      ["⬅", "LEFTWARDS BLACK ARROW", ""],
      ["⬆", "UPWARDS BLACK ARROW", ""],
      ["⬇", "DOWNWARDS BLACK ARROW", ""],
      ["⇨", "RIGHTWARDS WHITE ARROW", ""],
      ["⇦", "LEFTWARDS WHITE ARROW", ""],
    ],
  },
  {
    id: "maths", label: "Maths and logic", symbols: [
      ["=", "EQUALS SIGN", "equals"],
      ["≈", "ALMOST EQUAL TO", "approximately about"],
      ["≠", "NOT EQUAL TO", "not equal"],
      ["≡", "IDENTICAL TO", "identical equivalent"],
      ["≢", "NOT IDENTICAL TO", ""],
      ["≤", "LESS-THAN OR EQUAL TO", "less than or equal"],
      ["≥", "GREATER-THAN OR EQUAL TO", "greater than or equal"],
      ["≪", "MUCH LESS-THAN", ""],
      ["≫", "MUCH GREATER-THAN", ""],
      ["±", "PLUS-MINUS SIGN", "plus minus"],
      ["∓", "MINUS-OR-PLUS SIGN", ""],
      ["×", "MULTIPLICATION SIGN", "times multiply"],
      ["÷", "DIVISION SIGN", "divide"],
      ["⋅", "DOT OPERATOR", ""],
      ["−", "MINUS SIGN", "minus subtract"],
      ["∑", "N-ARY SUMMATION", "sum sigma total"],
      ["∏", "N-ARY PRODUCT", "product"],
      ["∫", "INTEGRAL", "integral"],
      ["∮", "CONTOUR INTEGRAL", ""],
      ["∂", "PARTIAL DIFFERENTIAL", "partial derivative"],
      ["∇", "NABLA", "nabla gradient"],
      ["∆", "INCREMENT", "delta change difference"],
      ["√", "SQUARE ROOT", "square root"],
      ["∛", "CUBE ROOT", ""],
      ["∞", "INFINITY", "infinity forever"],
      ["∝", "PROPORTIONAL TO", "proportional"],
      ["∀", "FOR ALL", "for all"],
      ["∃", "THERE EXISTS", "there exists"],
      ["∄", "THERE DOES NOT EXIST", ""],
      ["∈", "ELEMENT OF", "element of in member"],
      ["∉", "NOT AN ELEMENT OF", "not in"],
      ["∋", "CONTAINS AS MEMBER", ""],
      ["⊂", "SUBSET OF", ""],
      ["⊃", "SUPERSET OF", ""],
      ["⊆", "SUBSET OF OR EQUAL TO", ""],
      ["⊇", "SUPERSET OF OR EQUAL TO", ""],
      ["∪", "UNION", "union or"],
      ["∩", "INTERSECTION", "intersection and"],
      ["∅", "EMPTY SET", "empty set none"],
      ["∧", "LOGICAL AND", "and"],
      ["∨", "LOGICAL OR", "or"],
      ["¬", "NOT SIGN", "not negation"],
      ["⊕", "CIRCLED PLUS", "xor exclusive or"],
      ["⊗", "CIRCLED TIMES", ""],
      ["⊥", "UP TACK", ""],
      ["∥", "PARALLEL TO", ""],
      ["∠", "ANGLE", ""],
      ["∟", "RIGHT ANGLE", ""],
      ["∴", "THEREFORE", "therefore"],
      ["∵", "BECAUSE", "because"],
      ["≅", "APPROXIMATELY EQUAL TO", ""],
      ["∼", "TILDE OPERATOR", ""],
      ["≃", "ASYMPTOTICALLY EQUAL TO", ""],
      ["⊢", "RIGHT TACK", ""],
      ["⊨", "TRUE", ""],
      ["ℕ", "DOUBLE-STRUCK CAPITAL N", "natural numbers"],
      ["ℤ", "DOUBLE-STRUCK CAPITAL Z", "integers"],
      ["ℚ", "DOUBLE-STRUCK CAPITAL Q", ""],
      ["ℝ", "DOUBLE-STRUCK CAPITAL R", "real numbers"],
      ["ℂ", "DOUBLE-STRUCK CAPITAL C", ""],
      ["ℵ", "ALEF SYMBOL", ""],
      ["⌊", "LEFT FLOOR", ""],
      ["⌋", "RIGHT FLOOR", ""],
      ["⌈", "LEFT CEILING", ""],
      ["⌉", "RIGHT CEILING", ""],
      ["⟨", "MATHEMATICAL LEFT ANGLE BRACKET", ""],
      ["⟩", "MATHEMATICAL RIGHT ANGLE BRACKET", ""],
      ["½", "VULGAR FRACTION ONE HALF", "half"],
      ["⅓", "VULGAR FRACTION ONE THIRD", ""],
      ["⅔", "VULGAR FRACTION TWO THIRDS", ""],
      ["¼", "VULGAR FRACTION ONE QUARTER", "quarter"],
      ["¾", "VULGAR FRACTION THREE QUARTERS", "three quarters"],
      ["‰", "PER MILLE SIGN", "per mille"],
    ],
  },
  {
    id: "checks", label: "Checks and ballots", symbols: [
      ["✓", "CHECK MARK", "tick check done yes"],
      ["✔", "HEAVY CHECK MARK", "tick check done yes"],
      ["✕", "MULTIPLICATION X", "cross close no"],
      ["✖", "HEAVY MULTIPLICATION X", "cross close no"],
      ["✗", "BALLOT X", "cross no wrong"],
      ["✘", "HEAVY BALLOT X", "cross no wrong"],
      ["☐", "BALLOT BOX", "checkbox todo unchecked"],
      ["☑", "BALLOT BOX WITH CHECK", "checkbox done checked"],
      ["☒", "BALLOT BOX WITH X", "checkbox cancelled crossed"],
      ["⊠", "SQUARED TIMES", ""],
      ["⊡", "SQUARED DOT OPERATOR", ""],
      ["🗸", "LIGHT CHECK MARK", ""],
      ["🗴", "BALLOT SCRIPT X", ""],
    ],
  },
  {
    id: "shapes", label: "Stars and shapes", symbols: [
      ["★", "BLACK STAR", "star favourite rating"],
      ["☆", "WHITE STAR", "star rating empty"],
      ["✦", "BLACK FOUR POINTED STAR", ""],
      ["✧", "WHITE FOUR POINTED STAR", ""],
      ["✩", "STRESS OUTLINED WHITE STAR", ""],
      ["✪", "CIRCLED WHITE STAR", ""],
      ["✫", "OPEN CENTRE BLACK STAR", ""],
      ["✬", "BLACK CENTRE WHITE STAR", ""],
      ["✭", "OUTLINED BLACK STAR", ""],
      ["✮", "HEAVY OUTLINED BLACK STAR", ""],
      ["✯", "PINWHEEL STAR", ""],
      ["✰", "SHADOWED WHITE STAR", ""],
      ["●", "BLACK CIRCLE", "dot circle filled bullet"],
      ["○", "WHITE CIRCLE", "circle empty"],
      ["◉", "FISHEYE", ""],
      ["◎", "BULLSEYE", ""],
      ["◌", "DOTTED CIRCLE", ""],
      ["◍", "CIRCLE WITH VERTICAL FILL", ""],
      ["◐", "CIRCLE WITH LEFT HALF BLACK", ""],
      ["◑", "CIRCLE WITH RIGHT HALF BLACK", ""],
      ["◒", "CIRCLE WITH LOWER HALF BLACK", ""],
      ["◓", "CIRCLE WITH UPPER HALF BLACK", ""],
      ["◯", "LARGE CIRCLE", ""],
      ["⬤", "BLACK LARGE CIRCLE", ""],
      ["■", "BLACK SQUARE", "square filled"],
      ["□", "WHITE SQUARE", "square empty box"],
      ["▢", "WHITE SQUARE WITH ROUNDED CORNERS", ""],
      ["▣", "WHITE SQUARE CONTAINING BLACK SMALL SQUARE", ""],
      ["▪", "BLACK SMALL SQUARE", ""],
      ["▫", "WHITE SMALL SQUARE", ""],
      ["◼", "BLACK MEDIUM SQUARE", ""],
      ["◻", "WHITE MEDIUM SQUARE", ""],
      ["▬", "BLACK RECTANGLE", ""],
      ["▭", "WHITE RECTANGLE", ""],
      ["▮", "BLACK VERTICAL RECTANGLE", ""],
      ["▯", "WHITE VERTICAL RECTANGLE", ""],
      ["▲", "BLACK UP-POINTING TRIANGLE", "triangle up"],
      ["△", "WHITE UP-POINTING TRIANGLE", ""],
      ["▼", "BLACK DOWN-POINTING TRIANGLE", "triangle down"],
      ["▽", "WHITE DOWN-POINTING TRIANGLE", ""],
      ["▶", "BLACK RIGHT-POINTING TRIANGLE", "play right triangle"],
      ["▷", "WHITE RIGHT-POINTING TRIANGLE", ""],
      ["◀", "BLACK LEFT-POINTING TRIANGLE", "left triangle back"],
      ["◁", "WHITE LEFT-POINTING TRIANGLE", ""],
      ["◆", "BLACK DIAMOND", "diamond"],
      ["◇", "WHITE DIAMOND", "diamond empty"],
      ["◈", "WHITE DIAMOND CONTAINING BLACK SMALL DIAMOND", ""],
      ["⬟", "BLACK PENTAGON", ""],
      ["⬠", "WHITE PENTAGON", ""],
      ["⬡", "WHITE HEXAGON", ""],
      ["⬢", "BLACK HEXAGON", ""],
      ["⬣", "HORIZONTAL BLACK HEXAGON", ""],
      ["♠", "BLACK SPADE SUIT", ""],
      ["♣", "BLACK CLUB SUIT", ""],
      ["♥", "BLACK HEART SUIT", "heart love"],
      ["♦", "BLACK DIAMOND SUIT", ""],
      ["♤", "WHITE SPADE SUIT", ""],
      ["♧", "WHITE CLUB SUIT", ""],
      ["♡", "WHITE HEART SUIT", ""],
      ["♢", "WHITE DIAMOND SUIT", ""],
    ],
  },
  {
    id: "bullets", label: "Bullets and dingbats", symbols: [
      ["•", "BULLET", "bullet dot"],
      ["◦", "WHITE BULLET", "bullet hollow"],
      ["‣", "TRIANGULAR BULLET", "bullet triangle"],
      ["⁃", "HYPHEN BULLET", ""],
      ["∘", "RING OPERATOR", ""],
      ["⦿", "CIRCLED BULLET", ""],
      ["⦾", "CIRCLED WHITE BULLET", ""],
      ["❖", "BLACK DIAMOND MINUS WHITE X", ""],
      ["❯", "HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT", "chevron right"],
      ["❮", "HEAVY LEFT-POINTING ANGLE QUOTATION MARK ORNAMENT", "chevron left"],
      ["☛", "BLACK RIGHT POINTING INDEX", ""],
      ["☞", "WHITE RIGHT POINTING INDEX", ""],
      ["✎", "LOWER RIGHT PENCIL", "pencil edit"],
      ["✏", "PENCIL", ""],
      ["✐", "UPPER RIGHT PENCIL", ""],
      ["✂", "BLACK SCISSORS", "scissors cut"],
      ["✉", "ENVELOPE", "envelope email mail"],
      ["☎", "BLACK TELEPHONE", "telephone phone"],
      ["✆", "TELEPHONE LOCATION SIGN", ""],
      ["⚑", "BLACK FLAG", "flag"],
      ["⚐", "WHITE FLAG", ""],
      ["⚠", "WARNING SIGN", "warning caution alert"],
      ["⚡", "HIGH VOLTAGE SIGN", "lightning power fast"],
      ["☀", "BLACK SUN WITH RAYS", "sun weather"],
      ["☁", "CLOUD", "cloud weather"],
      ["☂", "UMBRELLA", ""],
      ["♪", "EIGHTH NOTE", "music note"],
      ["♫", "BEAMED EIGHTH NOTES", ""],
      ["☺", "WHITE SMILING FACE", ""],
      ["☹", "WHITE FROWNING FACE", ""],
      ["♻", "BLACK UNIVERSAL RECYCLING SYMBOL", "recycle"],
      ["⚙", "GEAR", "gear settings cog"],
      ["⌛", "HOURGLASS", "hourglass time wait"],
      ["⏳", "HOURGLASS WITH FLOWING SAND", ""],
      ["⌚", "WATCH", "watch time"],
      ["✈", "AIRPLANE", "plane travel"],
      ["☕", "HOT BEVERAGE", "coffee tea"],
      ["⚓", "ANCHOR", ""],
      ["☯", "YIN YANG", ""],
      ["☮", "PEACE SYMBOL", ""],
      ["♀", "FEMALE SIGN", ""],
      ["♂", "MALE SIGN", ""],
      ["⚥", "MALE AND FEMALE SIGN", ""],
      ["❤", "HEAVY BLACK HEART", ""],
      ["❦", "FLORAL HEART", ""],
      ["❧", "ROTATED FLORAL HEART BULLET", ""],
    ],
  },
  {
    id: "typography", label: "Punctuation and typography", symbols: [
      ["—", "EM DASH", "em dash"],
      ["–", "EN DASH", "en dash range"],
      ["‒", "FIGURE DASH", ""],
      ["…", "HORIZONTAL ELLIPSIS", "ellipsis dots"],
      ["·", "MIDDLE DOT", "middle dot interpunct"],
      ["¶", "PILCROW SIGN", "paragraph pilcrow"],
      ["§", "SECTION SIGN", "section"],
      ["†", "DAGGER", "dagger"],
      ["‡", "DOUBLE DAGGER", ""],
      ["©", "COPYRIGHT SIGN", "copyright"],
      ["®", "REGISTERED SIGN", "registered"],
      ["™", "TRADE MARK SIGN", "trademark"],
      ["℠", "SERVICE MARK", ""],
      ["№", "NUMERO SIGN", ""],
      ["¿", "INVERTED QUESTION MARK", ""],
      ["¡", "INVERTED EXCLAMATION MARK", ""],
      ["‽", "INTERROBANG", ""],
      ["⁂", "ASTERISM", ""],
      ["“", "LEFT DOUBLE QUOTATION MARK", "quote open"],
      ["”", "RIGHT DOUBLE QUOTATION MARK", "quote close"],
      ["‘", "LEFT SINGLE QUOTATION MARK", ""],
      ["’", "RIGHT SINGLE QUOTATION MARK", ""],
      ["„", "DOUBLE LOW-9 QUOTATION MARK", ""],
      ["‚", "SINGLE LOW-9 QUOTATION MARK", ""],
      ["«", "LEFT-POINTING DOUBLE ANGLE QUOTATION MARK", "guillemet quote"],
      ["»", "RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK", "guillemet quote"],
      ["‹", "SINGLE LEFT-POINTING ANGLE QUOTATION MARK", ""],
      ["›", "SINGLE RIGHT-POINTING ANGLE QUOTATION MARK", ""],
      ["′", "PRIME", ""],
      ["″", "DOUBLE PRIME", ""],
      ["‖", "DOUBLE VERTICAL LINE", ""],
      ["¦", "BROKEN BAR", ""],
      ["°", "DEGREE SIGN", "degree"],
      ["℃", "DEGREE CELSIUS", "celsius"],
      ["℉", "DEGREE FAHRENHEIT", "fahrenheit"],
      ["µ", "MICRO SIGN", "micro"],
      ["Ω", "OHM SIGN", "ohm"],
      ["ℓ", "SCRIPT SMALL L", ""],
      ["⌀", "DIAMETER SIGN", "diameter"],
      ["♯", "MUSIC SHARP SIGN", ""],
      ["♭", "MUSIC FLAT SIGN", ""],
      ["♮", "MUSIC NATURAL SIGN", ""],
      ["✱", "HEAVY ASTERISK", ""],
      ["⁎", "LOW ASTERISK", ""],
    ],
  },
  {
    id: "box", label: "Box drawing and blocks", symbols: [
      ["─", "BOX DRAWINGS LIGHT HORIZONTAL", "line horizontal"],
      ["│", "BOX DRAWINGS LIGHT VERTICAL", "line vertical"],
      ["┌", "BOX DRAWINGS LIGHT DOWN AND RIGHT", "corner"],
      ["┐", "BOX DRAWINGS LIGHT DOWN AND LEFT", ""],
      ["└", "BOX DRAWINGS LIGHT UP AND RIGHT", ""],
      ["┘", "BOX DRAWINGS LIGHT UP AND LEFT", ""],
      ["├", "BOX DRAWINGS LIGHT VERTICAL AND RIGHT", ""],
      ["┤", "BOX DRAWINGS LIGHT VERTICAL AND LEFT", ""],
      ["┬", "BOX DRAWINGS LIGHT DOWN AND HORIZONTAL", ""],
      ["┴", "BOX DRAWINGS LIGHT UP AND HORIZONTAL", ""],
      ["┼", "BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL", "cross"],
      ["═", "BOX DRAWINGS DOUBLE HORIZONTAL", ""],
      ["║", "BOX DRAWINGS DOUBLE VERTICAL", ""],
      ["╔", "BOX DRAWINGS DOUBLE DOWN AND RIGHT", ""],
      ["╗", "BOX DRAWINGS DOUBLE DOWN AND LEFT", ""],
      ["╚", "BOX DRAWINGS DOUBLE UP AND RIGHT", ""],
      ["╝", "BOX DRAWINGS DOUBLE UP AND LEFT", ""],
      ["╠", "BOX DRAWINGS DOUBLE VERTICAL AND RIGHT", ""],
      ["╣", "BOX DRAWINGS DOUBLE VERTICAL AND LEFT", ""],
      ["╦", "BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL", ""],
      ["╩", "BOX DRAWINGS DOUBLE UP AND HORIZONTAL", ""],
      ["╬", "BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL", ""],
      ["━", "BOX DRAWINGS HEAVY HORIZONTAL", ""],
      ["┃", "BOX DRAWINGS HEAVY VERTICAL", ""],
      ["┏", "BOX DRAWINGS HEAVY DOWN AND RIGHT", ""],
      ["┓", "BOX DRAWINGS HEAVY DOWN AND LEFT", ""],
      ["┗", "BOX DRAWINGS HEAVY UP AND RIGHT", ""],
      ["┛", "BOX DRAWINGS HEAVY UP AND LEFT", ""],
      ["╭", "BOX DRAWINGS LIGHT ARC DOWN AND RIGHT", ""],
      ["╮", "BOX DRAWINGS LIGHT ARC DOWN AND LEFT", ""],
      ["╯", "BOX DRAWINGS LIGHT ARC UP AND LEFT", ""],
      ["╰", "BOX DRAWINGS LIGHT ARC UP AND RIGHT", ""],
      ["╱", "BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT", ""],
      ["╲", "BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT", ""],
      ["╳", "BOX DRAWINGS LIGHT DIAGONAL CROSS", ""],
      ["┄", "BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL", ""],
      ["┆", "BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL", ""],
      ["┈", "BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL", ""],
      ["┊", "BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL", ""],
      ["░", "LIGHT SHADE", "shade light"],
      ["▒", "MEDIUM SHADE", ""],
      ["▓", "DARK SHADE", "shade dark"],
      ["█", "FULL BLOCK", "block full"],
      ["▀", "UPPER HALF BLOCK", ""],
      ["▄", "LOWER HALF BLOCK", ""],
      ["▌", "LEFT HALF BLOCK", ""],
      ["▐", "RIGHT HALF BLOCK", ""],
    ],
  },
  {
    id: "currency", label: "Currency", symbols: [
      ["$", "DOLLAR SIGN", "dollar"],
      ["€", "EURO SIGN", "euro"],
      ["£", "POUND SIGN", "pound sterling"],
      ["¥", "YEN SIGN", "yen yuan"],
      ["¢", "CENT SIGN", "cent"],
      ["₹", "INDIAN RUPEE SIGN", "rupee"],
      ["₽", "RUBLE SIGN", "rouble"],
      ["₩", "WON SIGN", "won"],
      ["₪", "NEW SHEQEL SIGN", "shekel"],
      ["₫", "DONG SIGN", ""],
      ["₺", "TURKISH LIRA SIGN", "lira"],
      ["₴", "HRYVNIA SIGN", ""],
      ["₦", "NAIRA SIGN", ""],
      ["₱", "PESO SIGN", ""],
      ["₿", "BITCOIN SIGN", "bitcoin"],
      ["₡", "COLON SIGN", ""],
      ["₲", "GUARANI SIGN", ""],
      ["₵", "CEDI SIGN", ""],
      ["₸", "TENGE SIGN", ""],
      ["₭", "KIP SIGN", ""],
      ["₮", "TUGRIK SIGN", ""],
      ["₼", "MANAT SIGN", ""],
      ["₾", "LARI SIGN", ""],
      ["¤", "CURRENCY SIGN", ""],
      ["ƒ", "LATIN SMALL LETTER F WITH HOOK", ""],
    ],
  },
  {
    id: "greek", label: "Greek letters", symbols: [
      ["Α", "GREEK CAPITAL LETTER ALPHA", ""],
      ["Β", "GREEK CAPITAL LETTER BETA", ""],
      ["Γ", "GREEK CAPITAL LETTER GAMMA", ""],
      ["Δ", "GREEK CAPITAL LETTER DELTA", ""],
      ["Ε", "GREEK CAPITAL LETTER EPSILON", ""],
      ["Ζ", "GREEK CAPITAL LETTER ZETA", ""],
      ["Η", "GREEK CAPITAL LETTER ETA", ""],
      ["Θ", "GREEK CAPITAL LETTER THETA", ""],
      ["Ι", "GREEK CAPITAL LETTER IOTA", ""],
      ["Κ", "GREEK CAPITAL LETTER KAPPA", ""],
      ["Λ", "GREEK CAPITAL LETTER LAMDA", ""],
      ["Μ", "GREEK CAPITAL LETTER MU", ""],
      ["Ν", "GREEK CAPITAL LETTER NU", ""],
      ["Ξ", "GREEK CAPITAL LETTER XI", ""],
      ["Ο", "GREEK CAPITAL LETTER OMICRON", ""],
      ["Π", "GREEK CAPITAL LETTER PI", ""],
      ["Ρ", "GREEK CAPITAL LETTER RHO", ""],
      ["Σ", "GREEK CAPITAL LETTER SIGMA", ""],
      ["Τ", "GREEK CAPITAL LETTER TAU", ""],
      ["Υ", "GREEK CAPITAL LETTER UPSILON", ""],
      ["Φ", "GREEK CAPITAL LETTER PHI", ""],
      ["Χ", "GREEK CAPITAL LETTER CHI", ""],
      ["Ψ", "GREEK CAPITAL LETTER PSI", ""],
      ["Ω", "GREEK CAPITAL LETTER OMEGA", ""],
      ["α", "GREEK SMALL LETTER ALPHA", ""],
      ["β", "GREEK SMALL LETTER BETA", ""],
      ["γ", "GREEK SMALL LETTER GAMMA", ""],
      ["δ", "GREEK SMALL LETTER DELTA", ""],
      ["ε", "GREEK SMALL LETTER EPSILON", ""],
      ["ζ", "GREEK SMALL LETTER ZETA", ""],
      ["η", "GREEK SMALL LETTER ETA", ""],
      ["θ", "GREEK SMALL LETTER THETA", ""],
      ["ι", "GREEK SMALL LETTER IOTA", ""],
      ["κ", "GREEK SMALL LETTER KAPPA", ""],
      ["λ", "GREEK SMALL LETTER LAMDA", ""],
      ["μ", "GREEK SMALL LETTER MU", ""],
      ["ν", "GREEK SMALL LETTER NU", ""],
      ["ξ", "GREEK SMALL LETTER XI", ""],
      ["ο", "GREEK SMALL LETTER OMICRON", ""],
      ["π", "GREEK SMALL LETTER PI", ""],
      ["ρ", "GREEK SMALL LETTER RHO", ""],
      ["σ", "GREEK SMALL LETTER SIGMA", ""],
      ["τ", "GREEK SMALL LETTER TAU", ""],
      ["υ", "GREEK SMALL LETTER UPSILON", ""],
      ["φ", "GREEK SMALL LETTER PHI", ""],
      ["χ", "GREEK SMALL LETTER CHI", ""],
      ["ψ", "GREEK SMALL LETTER PSI", ""],
      ["ω", "GREEK SMALL LETTER OMEGA", ""],
      ["ϑ", "GREEK THETA SYMBOL", ""],
      ["ϕ", "GREEK PHI SYMBOL", ""],
      ["ϵ", "GREEK LUNATE EPSILON SYMBOL", ""],
    ],
  },
  {
    id: "scripts", label: "Superscripts and subscripts", symbols: [
      ["⁰", "SUPERSCRIPT ZERO", ""],
      ["¹", "SUPERSCRIPT ONE", ""],
      ["²", "SUPERSCRIPT TWO", ""],
      ["³", "SUPERSCRIPT THREE", ""],
      ["⁴", "SUPERSCRIPT FOUR", ""],
      ["⁵", "SUPERSCRIPT FIVE", ""],
      ["⁶", "SUPERSCRIPT SIX", ""],
      ["⁷", "SUPERSCRIPT SEVEN", ""],
      ["⁸", "SUPERSCRIPT EIGHT", ""],
      ["⁹", "SUPERSCRIPT NINE", ""],
      ["⁺", "SUPERSCRIPT PLUS SIGN", ""],
      ["⁻", "SUPERSCRIPT MINUS", ""],
      ["⁼", "SUPERSCRIPT EQUALS SIGN", ""],
      ["⁽", "SUPERSCRIPT LEFT PARENTHESIS", ""],
      ["⁾", "SUPERSCRIPT RIGHT PARENTHESIS", ""],
      ["ⁿ", "SUPERSCRIPT LATIN SMALL LETTER N", ""],
      ["ⁱ", "SUPERSCRIPT LATIN SMALL LETTER I", ""],
      ["₀", "SUBSCRIPT ZERO", ""],
      ["₁", "SUBSCRIPT ONE", ""],
      ["₂", "SUBSCRIPT TWO", ""],
      ["₃", "SUBSCRIPT THREE", ""],
      ["₄", "SUBSCRIPT FOUR", ""],
      ["₅", "SUBSCRIPT FIVE", ""],
      ["₆", "SUBSCRIPT SIX", ""],
      ["₇", "SUBSCRIPT SEVEN", ""],
      ["₈", "SUBSCRIPT EIGHT", ""],
      ["₉", "SUBSCRIPT NINE", ""],
      ["₊", "SUBSCRIPT PLUS SIGN", ""],
      ["₋", "SUBSCRIPT MINUS", ""],
      ["₌", "SUBSCRIPT EQUALS SIGN", ""],
      ["₍", "SUBSCRIPT LEFT PARENTHESIS", ""],
      ["₎", "SUBSCRIPT RIGHT PARENTHESIS", ""],
      ["ₐ", "LATIN SUBSCRIPT SMALL LETTER A", ""],
      ["ₑ", "LATIN SUBSCRIPT SMALL LETTER E", ""],
      ["ₒ", "LATIN SUBSCRIPT SMALL LETTER O", ""],
      ["ₓ", "LATIN SUBSCRIPT SMALL LETTER X", ""],
      ["ₙ", "LATIN SUBSCRIPT SMALL LETTER N", ""],
      ["ₘ", "LATIN SUBSCRIPT SMALL LETTER M", ""],
      ["ₖ", "LATIN SUBSCRIPT SMALL LETTER K", ""],
    ],
  },
  {
    id: "keyboard", label: "Keyboard", symbols: [
      ["⌘", "PLACE OF INTEREST SIGN", "command cmd mac"],
      ["⌥", "OPTION KEY", "option alt mac"],
      ["⇧", "UPWARDS WHITE ARROW", "shift"],
      ["⌃", "UP ARROWHEAD", "control ctrl"],
      ["⎋", "BROKEN CIRCLE WITH NORTHWEST ARROW", "escape esc"],
      ["⏎", "RETURN SYMBOL", "return enter"],
      ["↵", "DOWNWARDS ARROW WITH CORNER LEFTWARDS", "return enter"],
      ["⌫", "ERASE TO THE LEFT", "backspace delete"],
      ["⌦", "ERASE TO THE RIGHT", "delete forward"],
      ["⇥", "RIGHTWARDS ARROW TO BAR", "tab"],
      ["⇤", "LEFTWARDS ARROW TO BAR", "shift tab back"],
      ["⇪", "UPWARDS WHITE ARROW FROM BAR", "caps lock"],
      ["␣", "OPEN BOX", "space"],
      ["⏏", "EJECT SYMBOL", "eject"],
      ["⌨", "KEYBOARD", "keyboard"],
      ["⎈", "HELM SYMBOL", ""],
      ["⇞", "UPWARDS ARROW WITH DOUBLE STROKE", "page up"],
      ["⇟", "DOWNWARDS ARROW WITH DOUBLE STROKE", "page down"],
      ["⏻", "POWER SYMBOL", "power"],
      ["⌤", "UP ARROWHEAD BETWEEN TWO HORIZONTAL BARS", "enter"],
      ["⎇", "ALTERNATIVE KEY SYMBOL", "alt option"],
    ],
  },
];

/** Unicode version the names above were taken from. */
export const SYMBOL_NAMES_UNICODE_VERSION = "16.0.0";
