import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { startDatabase } from './database-helpers.mjs';
test('real Postgres: generic modules, boundaries, retries, rollback and concurrent commit sequence',async()=>{
 const db=await startDatabase(); const {sql}=db;
 try {
 const org=crypto.randomUUID(),principal=crypto.randomUUID(),work=crypto.randomUUID(),messaging=crypto.randomUUID(),binding=crypto.randomUUID(),mb=crypto.randomUUID();
 await sql`insert into records_private.organisations(id,name) values(${org},'test')`;
 await sql`insert into records_private.principals(id) values(${principal})`;
 await sql`insert into records_private.memberships(org_id,id) values(${org},${principal})`;
 await sql`insert into records_private.datastores(id,org_id,module_id,api_major) values(${work},${org},'work',1),(${messaging},${org},'messaging',1)`;
 await sql`insert into records_private.bindings(id,datastore_id,principal_id,scopes) values(${binding},${work},${principal},ARRAY['work.read','work.write']),(${mb},${messaging},${principal},ARRAY['messaging.read','messaging.write'])`;
 await sql`insert into records_private.service_credentials(key_hash,binding_id) values(digest('test-key','sha256'),${binding})`;
 const auth=()=>sql.begin(async tx=>{await tx.unsafe('set local role records_gateway');return (await tx`select records.authenticate_api_key('test-key',${work}::uuid) result`)[0].result;});
 assert.equal((await auth()).subject,principal);
 await sql`update records_private.service_credentials set expires_at=now()-interval '1 second'`;
 await assert.rejects(auth(),e=>e.code==='PT401');
 await sql`update records_private.service_credentials set expires_at=null`;
 const claims=(ds=work,b=binding,scope=['work.read','work.write'])=>({iss:'records-gateway',aud:'records',sub:principal,org_id:org,datastore_id:ds,binding_id:b,scope,exp:Math.floor(Date.now()/1000)+600});
 const runtime=(fn,c=claims())=>sql.begin(async tx=>{await tx.unsafe('set local role records_runtime'); await tx`select set_config('request.jwt.claims',${JSON.stringify(c)},true)`;return fn(tx);});
 const command=(input,key='create',rev=null,cmd='work.create',ds=work,mod='work',c=claims())=>runtime(async tx=>(await tx`select records_api.execute_command(${ds}::uuid,${mod},1,${cmd},${tx.json(input)},${key},${rev}::bigint) result`)[0].result,c);
 const described=await runtime(async tx=>(await tx`select records_api.describe_datastore(${work}::uuid) result`)[0].result);assert.equal(described.module_id,'work');assert.deepEqual(described.granted_scopes,['work.read','work.write']);
 const first=await command({title:'A'}); assert.equal(first.seq,1);
 assert.deepEqual(await command({title:'A'}),first);
 await assert.rejects(command({title:'B'}),e=>e.code==='PT409');
 await assert.rejects(command({id:first.record.id,title:'B'},'update',null,'work.update'),e=>e.code==='PT428');
 await assert.rejects(command({id:first.record.id,title:'B'},'update',9,'work.update'),e=>e.code==='PT412');
 const edited=await command({id:first.record.id,title:'B'},'update',1,'work.update');assert.equal(edited.seq,2);
 await assert.rejects(command({title:123},'bad'),e=>e.code==='PT400');
 await assert.rejects(command({title:'no'},'scope',null,'work.create',work,'work',claims(work,binding,['work.read'])),e=>e.code==='PT403');
 await assert.rejects(runtime(tx=>tx.unsafe('select * from records_private.records')),e=>e.code==='42501');
 await assert.rejects(runtime(tx=>tx`select records_api.read_records(${messaging}::uuid,'messaging',1)`),e=>e.code==='PT403');
 await assert.rejects(runtime(tx=>tx`select records_api.pre_request()`,{...claims(),aud:undefined}),e=>e.code==='PT401');
 const sent=await command({channel:'general',body:'Hello'},'message',null,'messaging.send',messaging,'messaging',claims(messaging,mb,['messaging.read','messaging.write']));assert.equal(sent.seq,1);
 const inventory=crypto.randomUUID(),ib=crypto.randomUUID();
 const manifest=JSON.parse(await readFile(new URL('../../records-model/examples/inventory/module.json',import.meta.url),'utf8'));
 await sql.begin(async tx=>{await tx.unsafe(await readFile(new URL('../../records-model/examples/inventory/migrations/0001_initial.sql',import.meta.url),'utf8'));await tx`insert into records_private.modules values('inventory',1,${tx.json(manifest)})`;await tx`insert into records_private.commands values('inventory',1,'inventory.register','inventory.write','records_inventory.apply(uuid,text,jsonb,bigint,bigint)'::regprocedure)`;});
 await sql`insert into records_private.datastores(id,org_id,module_id,api_major) values(${inventory},${org},'inventory',1)`;
 await sql`insert into records_private.bindings(id,datastore_id,principal_id,scopes) values(${ib},${inventory},${principal},ARRAY['inventory.read','inventory.write'])`;
 const asset=await command({label:'Laptop',serial:'SER001'},'asset',null,'inventory.register',inventory,'inventory',claims(inventory,ib,['inventory.read','inventory.write']));assert.equal(asset.seq,1);assert.equal(asset.record.entity,'asset');
 await assert.rejects(runtime(tx=>tx`select records_api.read_records(${inventory}::uuid,'inventory',1)`),e=>e.code==='PT403');
 const model=await sql.begin(async tx=>{await tx.unsafe('set local role records_gateway');return (await tx`select records.get_model('inventory',1) model`)[0].model;});assert.deepEqual(model,manifest.profile);
 const duplicates=await Promise.all(Array.from({length:12},()=>command({title:'Concurrent'},'parallel')));assert(duplicates.every(r=>r.seq===3));
 await assert.rejects(runtime(async tx=>{await tx`select records_api.execute_command(${work}::uuid,'work',1,'work.create','{"title":"rollback"}'::jsonb,'rollback',null)`;throw Error('rollback');}),/rollback/);
 const many=await Promise.all(Array.from({length:12},(_,i)=>command({title:`${i}`},`key-${i}`)));assert.deepEqual(many.map(r=>r.seq).sort((a,b)=>a-b),Array.from({length:12},(_,i)=>i+4));
 const changes=await runtime(async tx=>(await tx`select records_api.pull_changes(${work}::uuid,0,500) result`)[0].result);// The first work command also journals the seven default workflow states (migration 010).
 assert.equal(changes.changes.filter(c=>c.entity==='work_item').length,15);assert.equal(changes.changes.length,22);assert.equal(changes.cursor,15);
 let signal; const locked=new Promise(resolve=>{signal=resolve;});
 const slow=runtime(async tx=>{const r=(await tx`select records_api.execute_command(${work}::uuid,'work',1,'work.create','{"title":"slow"}'::jsonb,'slow',null) result`)[0].result;signal();await tx`select pg_sleep(0.1)`;return r;});
 await locked;
 const fast=command({title:'fast'},'fast');
 assert.equal((await slow).seq,16);assert.equal((await fast).seq,17);
 const snapshot=await runtime(async tx=>(await tx`select records_api.snapshot_records(${work}::uuid,'work',1) result`)[0].result);assert.equal(snapshot.seq,17);assert.equal(snapshot.records.filter(r=>r.entity==='work_item').length,16);assert.equal(snapshot.records.length,23);assert.equal(snapshot.complete,true);
 await assert.rejects(runtime(tx=>tx`select records_api.snapshot_records(${work}::uuid,'work',1,1)`),e=>e.code==='PT413');
 await assert.rejects(runtime(tx=>tx`select records_api.read_records(${work}::uuid,null,null)`,claims(work,binding,[])),e=>e.code==='PT404');
 await assert.rejects(runtime(tx=>tx`select records_api.read_records(${work}::uuid,'work',1,null,null,null)`),e=>e.code==='PT400');
 await assert.rejects(runtime(tx=>tx`select records_api.pull_changes(${work}::uuid,0,null)`),e=>e.code==='PT400');
 const before=changes.permission_epoch;
 await sql`update records_private.bindings set scopes=ARRAY['work.read'] where id=${binding}`;
 await assert.rejects(runtime(tx=>tx`select records_api.pull_changes(${work}::uuid,0,100,${before})`),e=>e.code==='PT409');
 await assert.rejects(command({title:'revoked'},'revoked'),e=>e.code==='PT403');
 await sql`update records_private.bindings set active=false where id=${binding}`;
 await assert.rejects(runtime(tx=>tx`select records_api.read_records(${work}::uuid,'work',1)`),e=>e.code==='PT403');
 } finally {await db.stop();}
});
