import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { RecordsClient } from '../src/client.ts';

const enabled = process.env.RECORDS_INTEGRATION === '1';
test('real gateway → ES256 PostgREST → SQL, scoped modules, retries, conflicts, models and changes', { skip: !enabled }, async () => {
  const config = JSON.parse(await readFile(new URL('../.eval/client.json', import.meta.url), 'utf8'));
  const origin = process.env.RECORDS_TEST_URL ?? config.baseUrl;
  const work = new RecordsClient({ url: origin, datastore: config.work.datastoreId, token: () => config.work.key });
  const message = new RecordsClient({ url: origin, datastore: config.messaging.datastoreId, token: () => config.messaging.key });
  const path = `/v1/datastores/${config.work.datastoreId}`;
  const call = (suffix: string, key = config.work.key) => fetch(`${origin}${path}${suffix}`, { headers: { authorization: `Bearer ${key}` } });
  assert.equal((await call('/describe', 'invalid')).status, 401);
  const declared = await work.describe();
  assert.equal(declared.modules[0].id, 'work');
  await assert.rejects(work.bind({ moduleId: 'messaging', apiMajor: 1, scopes: [] }));
  const bound = await work.bind({ moduleId: 'work', apiMajor: 1, scopes: ['work.read', 'work.write'] });
  const idempotencyKey = crypto.randomUUID();
  const first = await work.command('work', 1, 'work.create', { title: 'Integration task', status: 'open' }, { idempotencyKey });
  assert.deepEqual(await work.command('work', 1, 'work.create', { title: 'Integration task', status: 'open' }, { idempotencyKey }), first);
  await assert.rejects(work.command('work', 1, 'work.create', { title: 'Changed' }, { idempotencyKey }), (e: any) => e.status === 409);
  await assert.rejects(work.command('work', 1, 'work.update', { id: first.record.id, status: 'done' }), (e: any) => e.status === 428);
  await assert.rejects(work.command('work', 1, 'work.update', { id: first.record.id, status: 'done' }, { revision: first.seq + 100 }), (e: any) => e.status === 412);
  const edited = await work.command('work', 1, 'work.update', { id: first.record.id, status: 'done' }, { revision: first.seq });
  assert.equal(edited.record.data.status, 'done');
  const snapshot = await work.snapshot('work', 1);
  assert.equal(snapshot.complete, true);
  assert(snapshot.records.some((r: any) => r.id === first.record.id));
  const contract = await call('/openapi');
  assert.equal(contract.status, 200);
  assert.match(await contract.text(), /work.create/);
  assert.equal((await call('/modules/messaging/v1/records')).status, 403);
  assert.equal((await fetch(`${origin}/v1/datastores/${config.messaging.datastoreId}/describe`, { headers: { authorization: `Bearer ${config.work.key}` } })).status, 401);
  const sent = await message.command('messaging', 1, 'messaging.send', { channel: 'general', body: 'Hello from integration' });
  assert.equal(sent.record.data.body, 'Hello from integration');
  const changes = await work.changes(first.seq - 1, first.permission_epoch);
  assert(changes.changes.some((c: any) => c.record_id === first.record.id));
  const jsonld = await call(`/modules/work/v1/records?id=${first.record.id}&format=jsonld`);
  assert.equal(jsonld.status, 200);
  assert.match(await jsonld.text(), /urn:records:datastore:/);
  const term = await fetch(`${origin}/v1/vocabulary/schemaorg/terms/Project`);
  assert.equal(term.status, 200); assert.match(await term.text(), /Project/);
  assert.equal((await fetch(`${origin}/v1/models/work/schema/work_item`)).status, 200);
  const controller = new AbortController();
  const stream = await fetch(`${origin}${path}/events`, { headers: { authorization: `Bearer ${config.work.key}` }, signal: controller.signal });
  assert.equal(stream.status, 200);
  const reader = stream.body!.getReader();
  assert.match(new TextDecoder().decode((await reader.read()).value), /event: changes/);
  controller.abort(); await reader.cancel().catch(() => {});
});
